### ISSUE TITLE
Intermittent 0 byte snapshots with S3 storage

### ISSUE THREAD

**Issue by tl-eddie-hoffman** [Lucretius/vault_raft_snapshot_agent#6]
Many thanks for creating this project. 

All working well except when using the S3 bucket storage for configuration I am seeing 0 byte snapshots intermittently. Version and encryption is enabled on the bucket. I have tried disabling these but the agent continues to upload 0 byte snapshots.

![image](https://user-images.githubusercontent.com/73109001/105346155-1b5e5880-5bdd-11eb-924e-00a6591cc2c7.png)

**Comment by Lucretius** [comment]
Hmm, not sure what would cause this - the snapshot is generated from the Raft Snapshot API and the same snapshot is then used by all of the enabled snapshot storage methods (AWS/Azure/GCP/etc.)  I wonder, have you tried enabling local file store writing as well to see if the same zero byte files get persisted to local disk?  If you could try that out, and the same zero byte files were to get generated, that would indicate something is wrong with the Raft snapshot API being invoked.  If not, then it would indicate something wrong with the S3 upload piece.

**Comment by tl-eddie-hoffman** [comment]
Couldn't get to the bottom of this, but it seems to be resolved in v0.2.1
